### ISSUE TITLE
Bug in multi_panel.py

### ISSUE THREAD

**Issue by Sarah-Kst** [Campbell-Muscle-Lab/PyCMLutilities#1]
The demo from PyCMLutil.py does not work properly because there is a bug ("'text' object has no property 'loc'") at line 321 from multi_panel.py (see Figure).

![demo_mutli](https://user-images.githubusercontent.com/65904084/103022399-2ffef080-454c-11eb-93a7-420254627535.PNG)

Bug is solved at the moment by commenting line 321. Ken believe this is related to an python updated package.

**Comment by redadev000** [comment]
I just tested the demo and it works fine for me. I am using python 3.8,  but in the other hand i got the following error, that i fixed by creating manually the folder temp:
Traceback (most recent call last):
  File "C:/Users/Reda/Desktop/git_projects/PyCMLutilities/PyCMLutil.py", line 16, in <module>
    pmc_util()
  File "C:/Users/Reda/Desktop/git_projects/PyCMLutilities/PyCMLutil.py", line 12, in pmc_util
    d.demos('plots_multi_panel')
  File "C:\Users\Redq\Desktop\git_projects\PyCMLutilities\demos\demos_code.py", line 25, in demos
    dmp.run_demos()
  File "C:\Users\Reda\Desktop\git_projects\PyCMLutilities\demos\demos_plots\demos_multi_panel\demos_multi_panel_code.py", line 18, in run_demos
    pymyovent_example()
  File "C:\Users\Reda\Desktop\git_projects\PyCMLutilities\demos\demos_plots\demos_multi_panel\demos_multi_panel_code.py", line 37, in pymyovent_example
    fig, ax = mp.multi_panel_from_flat_data(
  File "C:\Users\Reda\Desktop\git_projects\PyCMLutilities\plots\multi_panel.py", line 351, in multi_panel_from_flat_data
    fig.savefig(output_image_file_string, dpi=dpi)
  File "C:\Users\Reda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\Reda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "C:\Users\Reda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Reda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\backends\backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "C:\Users\Reda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Users\Reda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 2148, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\reda\\Desktop\\git_projects\\PyCMLutilities\\demos\\demos_plots\\demos_multi_panel\\temp/pymyovent.png'

**Comment by kenatcampbellmusclelab** [comment]
Thanks @redadev000 - we can fix your issue by adjusting the .gitignore to make sure the directory exists.

The original bug on this thread is fixed if you use matplotlib >= 3.3.2

**Comment by Sarah-Kst** [comment]
@kenatcampbellmusclelab For the temp directory, we can either add a .gitignore inside the temp folder telling to ignore everything inside it, or we can have the python script to check and create the temp directory if it does not exist initially. What is the best solution?
